# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name:  RDF Generator Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
      working-directory: ./tools/rdf_generator
    - name:  RDF Generator Tests
      run: |  
       python -m unittest discover -p '*_test.py' --failfast -v
      working-directory: ./tools/rdf_generator/rdfformat/tests
#     - name:  RDF Generator Tests Windows
#       if: matrix.os == 'windows-latest'
#       run: |
#        for %%G in ./tools/rdf_generator/rdfformat/tests/(*test.py); do python.exe %%G       
#       working-directory: ./tools/rdf_generator/rdfformat/tests
