# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Get Changed Files
      if: (matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest') 
      id: changed_files
      uses: trilom/file-changes-action@v1.2.3
      with:
        fileOutput: ' '
    - name: Select files to check
      if: (matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest') 
      run: |
        # Filter out non-python files.
        cat $HOME/files_added.txt $HOME/files_modified.txt | tr ' ' '\n' | grep '\.py$' > py_files.txt || true
        # Filter out non-test python files and e2e or integration tests.
        cat py_files.txt | grep '_test\.py$' | grep -v _e2e_ | grep -v integration | grep -v 'examples/' > py_test_files.txt || true
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name:  RDF Generator Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
      working-directory: ./tools/rdf_generator
    - name:  Python Tests Ubuntu & MacOs
      if: (matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest') 
      shell: bash
      run: |
         [ ! -s "py_test_files.txt" ] || cat py_test_files.txt | xargs -I {} python {}
      #  find . -name '*_test.py' -exec python '{}' \;       
        
      working-directory: ./tools/rdf_generator/rdfformat/tests
    - name:  Ontology Yaml Validator Install dependencies
      run: |
        python setup.py install
      working-directory: ./tools/validators/ontology_validator
    - name: Ontology Yaml Validator Generator Tests 
      if: (matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest') 
      run: find . -name '*_test.py' -exec python '{}' \;
      working-directory: ./tools/validators/ontology_validator/yamlformat/tests
      #     - name:  RDF Generator Tests Windows
#       if: matrix.os == 'windows-latest'
#       run: |
#          for %%G in (*test.py); do python.exe %%G       
#       working-directory: ./tools/rdf_generator/rdfformat/tests
